
  :enable_starttls_auto: true
  :address: smtp.gmail.com
  :port: 587
  :domain: gmail.com
  :authentication: :plain
  :user_name: vijay.ror@gmail.com
  :password: 
  :tls: true
  :host: imap.gmail.com
  :url_port: 993  